"""
generate_catalogue.py
Scans all tool .py files, extracts CATALOGUE METADATA blocks from module docstrings,
and outputs catalogue.yaml at the project root.

Usage:
    python report_agent/tools/generate_catalogue.py
    → generates catalogue.yaml in the project root

Output format:
    tools:
      - name: builder.exposure
        display_name: Calcul d'exposition (E_x, D_x)
        short_description: ...
        domain: mortality_experience
        capability_group: table_construction
        depends_on: [...]
        required_by: [...]
        client_visible: true
"""
from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
EXCLUDED_FILES = {
    "__init__.py",
    "TOOL_CONTRACT_TEMPLATE.py",
    "validate_contracts.py",
    "generate_catalogue.py",
    "_nb_loader.py",
    "tool_registry.py",
    "example.py",
}

# CATALOGUE METADATA section end marker
_SECTION_RE = re.compile(
    r"CATALOGUE METADATA\s*[-═]+\s*(.*?)(?:^\"\"\"|\Z)",
    re.DOTALL | re.MULTILINE,
)

# Key: value parser — handles list values like [a, b, c]
_KV_RE = re.compile(r"^([a-zA-Z_]+)\s*:\s*(.+)$", re.MULTILINE)


def _parse_value(raw: str):
    """Parse a raw string value from the catalogue block."""
    raw = raw.strip()
    # List value: [a, b, c] or [[a, b]]
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        # Remove nested brackets if present
        inner = inner.strip("[]")
        items = [s.strip().strip("'\"") for s in inner.split(",") if s.strip()]
        return items
    # Boolean
    if raw.lower() == "true":
        return True
    if raw.lower() == "false":
        return False
    return raw


def extract_catalogue_metadata(content: str) -> dict | None:
    """Extract the CATALOGUE METADATA block from a file's docstring."""
    # Find the module docstring
    try:
        tree = ast.parse(content)
    except SyntaxError:
        return None

    docstring = ast.get_docstring(tree)
    if not docstring:
        return None

    match = _SECTION_RE.search(docstring)
    if not match:
        return None

    block = match.group(1)
    meta = {}
    for m in _KV_RE.finditer(block):
        key = m.group(1).strip()
        val = _parse_value(m.group(2))
        meta[key] = val

    # Also capture the tool name from IDENTITY section
    identity_match = re.search(r"name\s+:\s+(.+)", docstring)
    if identity_match and "name" not in meta:
        meta["name"] = identity_match.group(1).strip()

    return meta if meta else None


def _yaml_value(v) -> str:
    """Serialize a Python value to YAML-compatible string."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, list):
        if not v:
            return "[]"
        items_str = ", ".join(f'"{item}"' if " " in str(item) else str(item) for item in v)
        return f"[{items_str}]"
    if isinstance(v, str):
        # Quote strings containing special chars
        if any(c in v for c in (":", "#", "{", "}", "[", "]", "&", "*", "?")):
            return f'"{v}"'
        return v
    return str(v)


def generate_yaml(tools: list[dict]) -> str:
    """Generate a YAML string from a list of tool metadata dicts."""
    lines = [
        "# Catalogue des tools disponibles — Agent Actuariat",
        "# Generated by generate_catalogue.py — do not edit manually.",
        "# Re-generate with: python report_agent/tools/generate_catalogue.py",
        "",
        "tools:",
    ]

    # Sort by domain then name
    tools_sorted = sorted(tools, key=lambda t: (t.get("domain", ""), t.get("name", "")))

    for tool in tools_sorted:
        lines.append(f"  - name: {tool.get('name', '[TO COMPLETE]')}")
        field_order = [
            "display_name", "short_description", "domain", "capability_group",
            "depends_on", "required_by", "client_visible",
        ]
        for field in field_order:
            if field in tool:
                val = _yaml_value(tool[field])
                lines.append(f"    {field}: {val}")
        # Any extra fields
        for k, v in tool.items():
            if k not in ("name",) + tuple(field_order):
                lines.append(f"    {k}: {_yaml_value(v)}")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    # Locate the project root (2 levels up from this file)
    tools_root = Path(__file__).parent
    project_root = tools_root.parent.parent

    # Collect .py files
    py_files = sorted(
        f for f in tools_root.rglob("*.py")
        if f.name not in EXCLUDED_FILES and "__pycache__" not in f.parts
    )

    tools: list[dict] = []
    domains: set[str] = set()

    for py_file in py_files:
        try:
            content = py_file.read_text(encoding="utf-8")
        except Exception as exc:
            print(f"  [WARN] Cannot read {py_file}: {exc}", file=sys.stderr)
            continue

        meta = extract_catalogue_metadata(content)
        if meta is None:
            print(f"  [SKIP] No CATALOGUE METADATA found: {py_file.relative_to(project_root)}")
            continue

        tools.append(meta)
        if "domain" in meta:
            domains.add(str(meta["domain"]))

    if not tools:
        print("No catalogue metadata found in any tool file.")
        return 1

    yaml_content = generate_yaml(tools)
    output_path = project_root / "catalogue.yaml"
    output_path.write_text(yaml_content, encoding="utf-8")

    print(
        f"Catalogue generated: {len(tools)} tools across {len(domains)} domains "
        f"→ {output_path}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
